---
title: "Untitled"
author: "r_data_types"
format: html
editor: visual
---

1.  Create a vector called vec_1

```{r}
vec_1 <- c(2, 5, 9, 10, 8, 12, 1, 0)

#Check the class of the vector 
class(vec_1)

#What type of variable does it store?
typeof(vec_1)

#Acces the 3rd element and store 
vec_1_e3 <- vec_1[3]

vec_1_e3

#Acces the 1st element and store 

vec_1_e1 <- vec_1[1]

vec_1_e1

#Access the 5th through 7th element 

vec_1_e5to7 <- vec_1[5:7]

vec_1_e5to7

#Reassign vec_1 as character stored as vec_1_char?

vec_1_char <- as.character(vec_1)

vec_1_char
```

2.  Create a vector called vec_2

```{r}
vec_2 <- c(town = "Santa Barbara", location = "Rincon", swell = "South")

#Check class
class(vec_2)

#Check length
length(vec_2)

#Access the second element by name and store
vec_2_e2 <- vec_2[2]

vec_2_e2

```

3.  Create a data frame in R, index

```{r}
df_1 <- data.frame(region = c("A", "B" , "A", "D"), 
                   species = c("otter", "great white", "sea lion", "gray whale"), 
                   count = c(12, 2, 36, 6))

#What is the class
class(df_1)

#Return class of species col
rude <- df_1$species

class(rude)

#Find the maximum value of count 
max_count <- max(df_1$count)

max_count
```

Practice accessing individual pieces of the data frame

```{}
```
